name: Nix stage
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  update-nix-package:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set output
        id: vars
        run: |
          tag="${GITHUB_REF#refs/*/}"
          echo "version=${tag:1}" >> $GITHUB_OUTPUT

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Install nurl from crates.io
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: nurl

      - name: Update default.nix version and hash
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.version }}
          REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
        run: |
          new_version="$RELEASE_VERSION"
          new_hash="$(nurl "$REPOSITORY_URL" "v$RELEASE_VERSION" --hash)"

          sed -i "s/version = \".*\";/version = \"$new_version\";/" default.nix
          sed -i "s#hash = \".*\";#hash = \"$new_hash\";#" default.nix

      - name: Create PR
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.version }}

          COMMITER_USERNAME: antigen-bot
          COMMITER_NAME: Antigen

          commiter_identity: Antigen <antigen.bot0@gmail.com>
        uses: peter-evans/create-pull-request@v4
        with:
          author: "${{ env.commiter_identity }}"
          base: main
          branch: nix-update-env
          delete-branch: true
          title: "Nix package update: new source version and hash (v${{ env.RELEASE_VERSION }})"
          commit-message: "bump(nix): v${{ env.RELEASE_VERSION }}"
          committer: "${{ env.commiter_identity }}"
          body: |
            Automated changes by [${{ env.COMMITER_NAME }}](https://github.com/${{ env.COMMITER_USERNAME }}).
